export const forumTags = [
  { name: "Python", color: "#3572A5" },
  { name: "Java", color: "#B07219" },
  { name: "JavaScript", color: "#F1E05A" },
  { name: "C++", color: "#F34B7D" },
  { name: "C#", color: "#178600" },
  { name: "Ruby", color: "#701516" },
  { name: "Swift", color: "#FFAC45" },
  { name: "Kotlin", color: "#F18E33" },
  { name: "PHP", color: "#4F5D95" },
  { name: "TypeScript", color: "#2B7489" },
  { name: "React", color: "#61DAFB" },
  { name: "Angular", color: "#B52E31" },
  { name: "Vue.js", color: "#42B883" },
  { name: "Node.js", color: "#68A063" },
  { name: "Django", color: "#092E20" },
  { name: "Flask", color: "#FF801F" },
  { name: "Spring", color: "#6DB33F" },
  { name: "Laravel", color: "#FF2D20" },
  { name: "Express.js", color: "#33B074" },
  { name: "TensorFlow", color: "#FF6F00" },
  { name: "HTML", color: "#E34F26" },
  { name: "CSS", color: "#1572B6" },
  { name: "Responsive Design", color: "#3F4C6B" },
  { name: "UI/UX Design", color: "#808080" },
  { name: "Bootstrap", color: "#563D7C" },
  { name: "Sass/Less", color: "#CC6699" },
  { name: "Web Accessibility", color: "#3D3D3D" },
  { name: "SEO", color: "#FF7F0E" },
  { name: "iOS Development", color: "#000000" },
  { name: "Android Development", color: "#3DDC84" },
  { name: "React Native", color: "#61DAFB" },
  { name: "Flutter", color: "#02569B" },
  { name: "Xamarin", color: "#3498DB" },
  { name: "Mobile UI Design", color: "#000000" },
  { name: "SQL", color: "#4479A1" },
  { name: "MySQL", color: "#336791" },
  { name: "PostgreSQL", color: "#336791" },
  { name: "MongoDB", color: "#439A45" },
  { name: "Firebase", color: "#FFCA28" },
  { name: "NoSQL", color: "#003A63" },
  { name: "SQLite", color: "#003B57" },
  { name: "Docker", color: "#2496ED" },
  { name: "Kubernetes", color: "#326CE5" },
  { name: "Jenkins", color: "#546E7A" },
  { name: "CI/CD", color: "#000000" },
  { name: "AWS", color: "#FF9900" },
  { name: "Azure", color: "#0089D6" },
  { name: "GCP", color: "#4285F4" },
  { name: "Terraform", color: "#623CE4" },
  { name: "Agile Methodology", color: "#F6C915" },
  { name: "Scrum", color: "#61AEDC" },
  { name: "Kanban", color: "#026E00" },
  { name: "Software Architecture", color: "#000000" },
  { name: "Design Patterns", color: "#000000" },
  { name: "Refactoring", color: "#000000" },
  { name: "Testing", color: "#FF3D00" },
  { name: "Windows", color: "#0078D6" },
  { name: "Linux", color: "#FCC624" },
  { name: "macOS", color: "#000000" },
  { name: "Unix", color: "#0045000" },
  { name: "Android", color: "#3DDC84" },
  { name: "iOS", color: "#000000" },
  { name: "Machine Learning", color: "#FF6F00" },
  { name: "Deep Learning", color: "#FF6F00" },
  { name: "NLP", color: "#FF6F00" },
  { name: "Computer Vision", color: "#FF6F00" },
  { name: "Reinforcement Learning", color: "#FF6F00" },
  { name: "Cybersecurity", color: "#D32F2F" },
  { name: "Ethical Hacking", color: "#689F38" },
  { name: "Penetration Testing", color: "#8E24AA" },
  { name: "Cryptography", color: "#7B1FA2" },
  { name: "Network Security", color: "#D32F" },
];

export interface Tag {
  name: string;
  color: string;
}
